// <auto-generated />
using Icarus;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace server.Migrations
{
    [DbContext(typeof(ScoreContext))]
    [Migration("20190217201813_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Icarus.Score", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("BaselineAltitude");

                    b.Property<string>("DateTime");

                    b.Property<string>("DisplayName");

                    b.Property<string>("LatLng");

                    b.Property<double>("PeakAltitude");

                    b.Property<string>("PhoneModel");

                    b.Property<double>("ThrowDuration");

                    b.Property<double>("baselineVerticalAccuracy");

                    b.Property<double>("peakVerticalAccuracy");

                    b.HasKey("ScoreId");

                    b.ToTable("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
